services:
  - type: web
    name: kpum-demo
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kpum-demo-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://kpum-demo-1.onrender.com
      - key: ENVIRONMENT
        value: production
      - key: REACT_APP_API_URL
        value: https://kpum-demo-1.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://kpum-demo-1.onrender.com/ws
      - key: REACT_APP_ENV
        value: production
    healthCheckPath: /api/status

databases:
  - name: kpum-demo-postgres
    databaseName: kpum_demo
    user: kpum_user 