services:
  - type: web
    name: kpum-demo-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile.prod
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://kpum-demo-backend.onrender.com
      - key: REACT_APP_WS_URL
        value: wss://kpum-demo-backend.onrender.com/ws
      - key: REACT_APP_ENV
        value: production
    healthCheckPath: /health

  - type: web
    name: kpum-demo-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerContext: ./backend
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kpum-demo-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://kpum-demo-frontend.onrender.com
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /api/status

databases:
  - name: kpum-demo-postgres
    databaseName: kpum_demo
    user: kpum_user 